name: CDKer
version: '6.0.2'
main: org.baicaizhale.cDKer.CDKer
api-version: '1.18'
description: A powerful CDK management plugin for Spigot servers
authors: [baicaizhale,zip8919]

commands:
  cdk:
    description: CDK management command
    usage: |
      §6=== CDK Plugin Usage ===
      §f/cdk create <amount> <commands> [uses] [note] [expire] [type] §7- Create CDK
      §f/cdk set <id/cdk> <identifier> <type> <value> §7- Set CDK property
      §f/cdk add <id/cdk> <identifier> <amount> §7- Add uses
      §f/cdk query <id/cdk> <identifier> §7- Query CDK info
      §f/cdk del <id/cdk> <identifier> §7- Delete CDK
      §f/cdk use <cdkcode> §7- Use CDK
      §f/cdk list §7- List all CDKs
      §f/cdk reload §7- Reload config
      §f/cdk log §7- Show CDK usage logs (permission: cdk.log)
    aliases: [cdker]

permissions:
  cdk.admin:
    description: Gives access to all CDK plugin commands
    default: op
    children:
      cdk.use: true
      cdk.create: true
      cdk.query: true
  
  cdk.use:
    description: Allows using CDK codes
    default: true
  
  cdk.create:
    description: Allows creating new CDK codes
    default: op
    children:
      cdk.query: true
  
  cdk.query:
    description: Allows querying CDK information
    default: op

  cdk.log:
    description: Allows viewing CDK usage logs
    default: op