name: CDKer
version: '4.0.0'
main: org.baicaizhale.cDKer.CDKer
api-version: '1.18'
commands:
  cdk:
    description: 用于兑换礼品码
    usage: /cdk <cdkCode>
  mcdk:
    description: 管理兑换码的命令
    usage: /mcdk <subcommand>
    permission: cdk.list
    subcommands:
      list:
        description: 查看兑换码列表
        usage: /mcdk list
      reload:
        description: 重载插件配置
        usage: /mcdk reload
        permission: cdk.reload
    tab-completer: org.baicaizhale.cDKer.CDKTabCompleter
permissions:
  cdk.list:
    description: 允许查看兑换码列表
    default: op
